### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by golfingal72** [flochaz/federated-appsync-api-demo#3]
I have downloaded the demo and am trying to get it to work...

I did:
`npm install -g aws-cdk`

Then I tried: 

npm ci (also tried npm install) with same results

`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/***/code/federated-appsync-api-demo/node_modules/aws-cdk/bin/cdk
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/***/code/federated-appsync-api-demo/node_modules/aws-cdk/bin/cdk'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`

**Comment by golfingal72** [comment]
need to run with node version > 16.0.0... got farther with that...  should document

**Comment by golfingal72** [comment]
instructions should also note that you have to run the cdk bootstrap

**Comment by flochaz** [comment]
Thanks for reporting this, sorry about that, I'll add extra instruction.
